services:
  - type: web
    name: stonks-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
